import React from 'react'
import Head from 'next/head'
import {Box, Typography, Paper, TextField} from "@mui/material";
import {useEnqueueSnackbar} from "@/components/hooks/useSnackbar";
import {API} from "@/utils/API";
import background from '../../public/background.jpg'
import Image from 'next/image'

const Home = () => {
    const [form, setForm] = React.useState({
        name: '',
        nickname: '',
        email: '',
        phone: '',
    })
    const [isLoading, setIsLoading] = React.useState(false)
    const {openSnackbar} = useEnqueueSnackbar()
    const getUsers = async () => {
        setIsLoading(true)
        try {
            const response = await API.get('/')
            if (response.status === 200) {

            }
        } catch (e) {
            openSnackbar({message: e.response?.data?.detail ? e.response.data.detail : e.message, variant: 'error'})
        } finally {
            setIsLoading(false)
        }
    }
    React.useEffect(() => {
        getUsers()
    }, [])

    const handleChange = (stateKey, value) => {
        setForm({...form, [stateKey]: value})
    }

    return (
        <Box display='flex' height='100vh'>
            <Box width='50%' display='flex' justifyContent='center' alignItems='center'>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app"/>
                    <meta name="viewport" content="width=device-width, initial-scale=1"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                <Box width='50%' mt='10px' display='flex' gap='10px' flexDirection='column'>
                    <Paper elevation={2}>
                        <TextField
                            label="Имя"
                            onChange={handleChange}
                            fullWidth
                            value={form.name}
                            variant="outlined"
                        />
                    </Paper>
                    <Paper elevatiton={2}>
                        <TextField
                            label="Nickname"
                            onChange={handleChange}
                            fullWidth
                            value={form.nickname}
                            variant="outlined"
                        />
                    </Paper>
                    <Paper elevation={2}>
                        <TextField
                            label="Почта"
                            onChange={handleChange}
                            fullWidth
                            value={form.email}
                            variant="outlined"
                        />
                    </Paper>
                    <Paper elevation={2}>
                        <TextField
                            label="Телефон"
                            onChange={handleChange}
                            fullWidth
                            value={form.phone}
                            variant="outlined"
                        />
                    </Paper>
                    <Box>
                        <Typography fontWeight={600}>Инструкция</Typography>
                    </Box>
                    <Box component='ul'>
                        <Typography component='li'>
                            Перейдите по ссылке
                        </Typography>
                        <Typography component='li'>
                            В левом верхнем углу файла найдите "Создать копию", назовите таблицу, cохраните.
                        </Typography>
                        <Typography component='li'>
                            Заполните ее.
                        </Typography>
                        <Typography component='li'>
                            В правом верхнем углу найдите "Настройки доступа", "Общий доступ", "Все у кого
                            есть
                            ссылка", "Копировать ссылку"
                        </Typography>
                    </Box>
                    <Typography href='https://google.com' component='a'>Таблица</Typography>
                </Box>
            </Box>
            <Box className='image-container'>
                <Image src={background} fill/>
            </Box>
        </Box>
    )
}

export default Home
